
trigger:
- main

pool:
   name: Test Agent

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - script: echo build FirstJob
  - job: SecondJob
    steps:
    - script: echo build SecondJob
- stage: DevDeploy
  jobs:
  - job: DevDeployJob
    steps:
    - script: echo DevDeployJob
  
- stage: QAdeploy
  jobs:
  - job: QADeployJob
    steps:
    - script: echo QADeployJob 
- stage: Proddeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - script: echo ProdDeployJob


#in this we have only one job otherwise we can run multiple jobs we must add stages

