
trigger:
- main

pool:
   name: Test Agent

stages:
- stages: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo build FirstJob
  - job: SecondJob
    steps:
    - bash: echo build SecondJob
- stages: DevDeploy
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo DevDeployJob
  
- stages: QAdeploy
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo QADeployJob 
- stages: Proddeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo ProdDeployJob

steps:
- script: echo Job1 Step1!
  displayName: 'Run a one-line script'
#in this we have only one job otherwise we can run multiple jobs we must add stages

