
trigger:
- main

pool:
   name: Test Agent

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - script: echo build FirstJob
  - job: SecondJob
    steps:
    - script: echo Build SecondJob
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
    - script: echo DevDeployJob
- stage: QADeploy
  dependsOn: Build
  jobs:
    - job: QADeployJob
      steps:
      - script: echo QADeployJob
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
    - job: ProdDeployJob
      steps:
      - script: echo ProdDeployJob


#in this we have only one job otherwise we can run multiple jobs we must add stages

